name: "Channel Invites Acceptances"
run-name: "cron to review acceptances"
#on:
#  schedule:
#    - cron: "0 0 * * 0"

jobs:
  cron:
    runs-on: "ubuntu-latest"
    env:
      INVITE_PROD: ${{ secrets.ST_INVITE_PRODUCTION }}
      INVITE_DEV: ${{ secrets.ST_INVITE_DEVELOP }}
      ST_TOKEN: ${{ secrets.ST_PAT }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: "setup smartthings cli"
        uses: "actions/setup-node@v3"
        with:
          node-version: "20.9.0"
      - run: "npm install --global @smartthings/cli@1.8.0"

      - name: "setup python"
        uses: "actions/setup-python@v3"
        with:
          python-version: 3.11

      - name: "update dev channel information"
        uses: "actions/checkout@v3"
        with:
          ref: "develop"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: |
          # git config user.email "erickvneri@github";
          # git config user.name "erickvneri";


          echo "Main invite:"
          smartthings edge:channels:invites $INVITE_DEV --json --token $ST_TOKEN

          #
          # Temporarily removing fs transaction
          #
          # ./scripts/track_acceptances.sh $INVITE_DEV $ST_TOKEN && \
          # git add README.md && \
          # git commit -m "cron: update acceptances count" && \
          # git push;

      - name: "update production channel information"
        uses: "actions/checkout@v3"
        with:
          ref: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: |
          git config user.email "erickvneri@github";
          git config user.name "erickvneri";

          #
          # bruteforced invite UUIDs, nothing to worry about,
          # I'll fix it later =]
          #
          echo "Main invite:"
          smartthings edge:channels:invites 82d9761d-7ce1-4897-9ffe-22b2b24e922b --json --token $ST_TOKEN
          echo "Secondary invite:"
          smartthings edge:channels:invites eba03afe-0f26-43b2-95e1-a0dde8011ebe --json --token $ST_TOKEN

          ./scripts/track_acceptances.sh $INVITE_PROD $ST_TOKEN && \
          #
          # Temporarily removing fs transaction
          #
          # git add README.md && \
          # git commit -m "cron: update acceptances count" && \
          # git push;
